INSERT INTO ANNUAIRE ( ID, NOM ) VALUES (1, 'Administrateur');
INSERT INTO ABONNE ( ID, LOGIN, MDP, ADMINISTRATOR, ABONNEMENT_ID) VALUES (1, 'admin', '$2a$10$FelDXHpr2GALBanos4US5.VCr6TttqLsMjYRAy9hiXNsQhz2ur.a.', TRUE, 1);
INSERT INTO PARTICULIER ( ID, NOM, PRENOM ) VALUES (1, 'Pierson', 'Guillaume');
